praguelabs/Models/Invoice.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praguelabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.orders = new HashSet<order>();
        }
    
        public int ID { get; set; }
        public string invoiceNum { get; set; }
        public Nullable<int> storeID { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public string paid { get; set; }
    
        public virtual store store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}

praguelabs/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using praguelabs.Models;
using System.Net.Http;
using System.Threading.Tasks;

namespace praguelabs.Controllers
{
    public class InvoicesController : Controller
    {
        private pragueLabsEntities db = new pragueLabsEntities();
        //private string apiKey = "178bad9817b07e2063a45f5158a6eeff467733ff133fa5141322166416def40b";
        // GET: Invoices
        public ActionResult Index()
        {
            var invoices = db.Invoices.Include(i => i.store);
            return View(invoices.ToList());
        }
        public async Task<ActionResult> notPaid()
        {
            var client = new HttpClient();
            //Response.AddHeader("APIKey", apiKey);
            var response = await client.GetAsync("http://praguelabs.apphb.com/api/Payment");
            var invoices = await response.Content.ReadAsAsync<IEnumerable<Invoice>>();
            //var invoices = db.Invoices.Include(i => i.store);
            return View(invoices);
        }

        // GET: Invoices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // GET: Invoices/Create
        public ActionResult Create()
        {
            ViewBag.storeID = new SelectList(db.stores, "ID", "name");
            return View();
        }

        // POST: Invoices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,invoiceNum,storeID,orderDate,paid")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                invoice.orderDate = DateTime.Now;
                db.Invoices.Add(invoice);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.storeID = new SelectList(db.stores, "ID", "name", invoice.storeID);
            return View(invoice);
        }

        // GET: Invoices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            ViewBag.storeID = new SelectList(db.stores, "ID", "name", invoice.storeID);
            return View(invoice);
        }

        // POST: Invoices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,invoiceNum,storeID,orderDate,paid")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invoice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.storeID = new SelectList(db.stores, "ID", "name", invoice.storeID);
            return View(invoice);
        }

        // GET: Invoices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // POST: Invoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invoice invoice = db.Invoices.Find(id);
            db.Invoices.Remove(invoice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

praguelabs/Views/Invoices/Create.cshtml
@model praguelabs.Models.Invoice

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Invoice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.invoiceNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.invoiceNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.invoiceNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.storeID, "storeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("storeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.storeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.orderDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.orderDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.orderDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.paid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("paid", new List<SelectListItem> {
                    new SelectListItem { Text="paid", Value="yes" },
                    new SelectListItem { Text="Not paid", Value="No" }
               }, "Select Payment Status", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.paid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

praguelabs/Views/Invoices/Delete.cshtml
@model praguelabs.Models.Invoice

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.invoiceNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.invoiceNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.orderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.orderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.paid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.store.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.store.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

praguelabs/Views/Invoices/Details.cshtml
@model praguelabs.Models.Invoice

@{
    ViewBag.Title = "Details";
}
<div class="toReload">
    <h2>Details</h2>

    <div>
        <h4>Invoice</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.invoiceNum)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.invoiceNum)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.orderDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.orderDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.paid)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.paid)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.store.name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.store.name)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index") |
        <button class="btn btn-success btn-sm" id="btnPayment">Pay this</button>
    </p>
</div>
<script>
    $(document).ready(function () {
        $("#btnPayment").click(function () {
            var id = @Model.ID;
            $.post("/api/Payment/PayInvoice?id=" + id ,{"id":id}, function (data) {
                //$('hr').remove();
                //$('footer').remove();
                $("body").load('@(Url.Action("Details", "Invoices", null, Request.Url.Scheme))');
                return false;
            },"json")
        });
    });
</script>

praguelabs/Views/Invoices/Edit.cshtml
@model praguelabs.Models.Invoice

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Invoice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.invoiceNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.invoiceNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.invoiceNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.storeID, "storeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("storeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.storeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.orderDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.orderDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.orderDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.paid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("paid", new List<SelectListItem> {
                    new SelectListItem { Text="paid", Value="yes" },
                    new SelectListItem { Text="Not paid", Value="No" }
               }, "Select Payment Status", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.paid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

praguelabs/Views/Invoices/Index.cshtml
@model IEnumerable<praguelabs.Models.Invoice>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.invoiceNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.orderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.paid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.store.name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.invoiceNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.orderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.paid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.store.name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

praguelabs/Views/Invoices/notPaid.cshtml
@model IEnumerable<praguelabs.Models.Invoice>

@{
    ViewBag.Title = "notPaid";
}

<h2>notPaid</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.invoiceNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.orderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.paid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.store.name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.invoiceNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.orderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.paid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.store.name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>